# Generated by Django 3.2.4 on 2021-06-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_admin'),
        ('users', '0003_auto_20210627_1550'),
    ]

    operations = [
    ]
