# Generated by Django 3.2.4 on 2021-07-06 13:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('assembly_line_id', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('assembly_line_name', models.TextField(blank=True)),
                ('person_name', models.TextField(help_text='Name of the person in charge')),
                ('output', models.FilePathField(help_text='Link of the output folder', path='media/documents/job_documents/output')),
                ('job_name', models.CharField(help_text='e.g develop website', max_length=300)),
                ('target_date', models.DateTimeField(help_text='e.g 2021-10-25 14:30:59', null=True)),
                ('total_budget', models.PositiveIntegerField(help_text='e.g currency AED')),
                ('job_description', models.CharField(help_text='e.g car website', max_length=1000, verbose_name='job description')),
                ('job_sample', models.FileField(upload_to='images/job_documents/job_samples')),
                ('job_instructions', models.FileField(null=True, upload_to='images/job_documents/job_instructions')),
                ('job_quantity', models.IntegerField(help_text='e.g Quantity of Job')),
                ('input_folder', models.FilePathField(help_text='Link of the Input folder', path='media/documents/job_documents/input')),
                ('job_status', models.CharField(choices=[('cr', 'Created'), ('as', 'Assigned'), ('ur', 'Under review'), ('co', 'Completed')], default='cr', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jobstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MicroTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microtask_name', models.CharField(help_text='e.g develop website', max_length=300)),
                ('microtask_category', models.CharField(max_length=300)),
                ('job_cost', models.PositiveIntegerField(default=0, help_text='currency AED', validators=[django.core.validators.MinValueValidator(0)])),
                ('time_required', models.PositiveIntegerField(default=1, help_text='In Hours', validators=[django.core.validators.MinValueValidator(1)])),
                ('skills', models.CharField(help_text='e.g coding, data entry', max_length=500, verbose_name='skills')),
                ('people_required_for_valid_tc', models.PositiveIntegerField(help_text='number of people required e.g 2', validators=[django.core.validators.MinValueValidator(1)])),
                ('job_sample', models.FileField(upload_to='job_documents/job_samples/')),
                ('job_instructions', models.FileField(upload_to='job_documents/job_instructions/')),
                ('tc_type', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic')], default='Manual', help_text='e.g Senior developer, tester & client', max_length=1, verbose_name='type of tc to be done')),
            ],
        ),
        migrations.CreateModel(
            name='MTOJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.IntegerField(help_text='related to MTO')),
                ('due_date', models.DateTimeField()),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('fees', models.FloatField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('rating_evaluation', models.IntegerField(null=True)),
                ('payment_status', models.CharField(choices=[('uninitiated', 'uninitiated'), ('pending', 'pending'), ('paid', 'paid')], default='uninitiated', max_length=100)),
                ('job_status', models.CharField(choices=[('in', 'in progress'), ('sub', 'submitted'), ('co', 'Completed')], default='in', max_length=100)),
                ('completed_date', models.DateTimeField(null=True)),
                ('output_path', models.FileField(upload_to=jobs.models.output_directory_path)),
                ('is_submitted', models.BooleanField(default=False)),
                ('evaluation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.evaluationstatus')),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='MTOAdminUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('varal_role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.adminroles')),
            ],
            options={
                'verbose_name_plural': 'MTO Admin Users',
            },
            bases=('users.user',),
        ),
        migrations.AddField(
            model_name='jobs',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.microtask'),
        ),
    ]
