# Generated by Django 3.2.4 on 2021-07-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microtask',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='microtask',
            name='sample',
        ),
    ]
