# Generated by Django 3.2.4 on 2021-07-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210701_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtojob',
            name='assigned_date',
            field=models.DateTimeField(),
        ),
    ]
