# Generated by Django 3.2.4 on 2021-07-06 03:19

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210706_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtask',
            name='instructions',
            field=models.FileField(default='na', upload_to=jobs.models.instructions_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microtask',
            name='sample',
            field=models.FileField(default='na', upload_to=jobs.models.sample_directory_path),
            preserve_default=False,
        ),
    ]
