# Generated by Django 3.2.4 on 2021-06-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210621_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MALRequirement',
        ),
    ]
