# Generated by Django 3.2.4 on 2021-07-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_mtojob_assigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtojob',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
