# Generated by Django 3.2.4 on 2021-07-04 09:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_mtojob_assigned_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'Mal Requirement', 'verbose_name_plural': 'Mal Requirements'},
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='job_cost',
            new_name='total_budget',
        ),
        migrations.RenameField(
            model_name='microtask',
            old_name='people_required',
            new_name='people_required_for_valid_tc',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='people_required',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='posted_date',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='microtask',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='microtask',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='microtask',
            name='job_name',
        ),
        migrations.RemoveField(
            model_name='microtask',
            name='quantity_job',
        ),
        migrations.RemoveField(
            model_name='microtask',
            name='target_date',
        ),
        migrations.AddField(
            model_name='jobs',
            name='assembly_line_id',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AddField(
            model_name='jobs',
            name='assembly_line_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AddField(
            model_name='jobs',
            name='input_folder',
            field=models.FilePathField(default='na', help_text='Link of the Input folder', path='media/documents/job_documents/input'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='output',
            field=models.FilePathField(default='na', help_text='Link of the output folder', path='media/documents/job_documents/output'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='person_name',
            field=models.TextField(default='na', help_text='Name of the person in charge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microtask',
            name='microtask_category',
            field=models.CharField(default='na', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microtask',
            name='microtask_name',
            field=models.CharField(default='na', help_text='e.g develop website', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='cat_id',
            field=models.CharField(max_length=50, verbose_name='cat_id'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.microtask'),
        ),
        migrations.AlterField(
            model_name='microtask',
            name='tc_type',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic')], default='Manual', help_text='e.g Senior developer, tester & client', max_length=1, verbose_name='type of tc to be done'),
        ),
        migrations.AlterField(
            model_name='microtask',
            name='time_required',
            field=models.PositiveIntegerField(default=1, help_text='In Hours', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='MALRequirement',
        ),
        migrations.DeleteModel(
            name='MTOJobCategory',
        ),
    ]
