# Generated by Django 3.2.4 on 2021-06-22 08:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_delete_malrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MALRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('assembly_line_id', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('assembly_line_name', models.TextField()),
                ('person_name', models.TextField(help_text='Name of the person in charge')),
                ('person_email', models.EmailField(max_length=254, null=True)),
                ('output', models.FilePathField(help_text='Link of the output folder', path='job_documents/output')),
                ('micro_task', models.CharField(max_length=300)),
                ('micro_task_category', models.CharField(max_length=300, null=True)),
                ('target_date', models.DateField()),
                ('total_budget', models.IntegerField(help_text='Total budget allocated for the job')),
                ('job_description', models.TextField()),
                ('job_sample', models.FileField(upload_to='job_documents/sample')),
                ('job_instructions', models.FileField(upload_to='job_documents/instruction')),
                ('job_quantity', models.IntegerField()),
                ('input_folder', models.FilePathField(help_text='Link of the Input folder', path='job_documents/input')),
            ],
            options={
                'verbose_name': 'Mal Requirement',
                'verbose_name_plural': 'Mal Requirements',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(help_text='e.g develop website', max_length=300)),
                ('target_date', models.DateTimeField(help_text='e.g 2021-10-25 14:30:59', null=True)),
                ('job_description', models.CharField(help_text='e.g car website', max_length=1000, verbose_name='job description')),
                ('job_sample', models.FileField(upload_to='images/job_documents/job_samples')),
                ('job_quantity', models.IntegerField(help_text='e.g Quantity of Job')),
                ('people_required', models.PositiveIntegerField(help_text='e.g number of people required e.g 2', validators=[django.core.validators.MinValueValidator(1)])),
                ('skills', models.CharField(help_text='e.g coding, data entry', max_length=500, verbose_name='skills')),
                ('job_cost', models.PositiveIntegerField(help_text='e.g currency AED')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.malrequirement')),
            ],
        ),
    ]
