# Generated by Django 3.2.4 on 2021-06-24 07:55

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobs_malrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status_name', models.CharField(choices=[('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Approved', 'Approved')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='MTORoles',
            new_name='AdminRoles',
        ),
        migrations.AlterModelManagers(
            name='mtoadminuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_instructions',
            field=models.FileField(null=True, upload_to='images/job_documents/job_instructions'),
        ),
        migrations.AlterField(
            model_name='evaluationstatus',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='malrequirement',
            name='assembly_line_id',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='malrequirement',
            name='assembly_line_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='malrequirement',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='malrequirement',
            name='input_folder',
            field=models.FilePathField(help_text='Link of the Input folder', path='media/documents/job_documents/input'),
        ),
        migrations.AlterField(
            model_name='malrequirement',
            name='output',
            field=models.FilePathField(help_text='Link of the output folder', path='media/documents/job_documents/output'),
        ),
        migrations.AlterField(
            model_name='mtojob',
            name='assigned_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mtojob',
            name='completed_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mtojob',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs'),
        ),
        migrations.AlterField(
            model_name='mtojob',
            name='output_path',
            field=models.FileField(upload_to='images/job_documents/job_submissions'),
        ),
        migrations.AlterField(
            model_name='mtojob',
            name='rating_evaluation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mtojob',
            name='payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.paymentstatus', verbose_name='payment status'),
        ),
    ]
