# Generated by Django 3.2.4 on 2021-07-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20210704_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={},
        ),
        migrations.AlterField(
            model_name='jobs',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.microtask'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_name',
            field=models.CharField(help_text='e.g develop website', max_length=300),
        ),
    ]
