# Generated by Django 3.2.4 on 2021-07-04 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210704_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.jobstatus'),
        ),
    ]
