# Generated by Django 3.2.4 on 2021-06-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_mtojob_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtojob',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs'),
        ),
        migrations.AlterField(
            model_name='mtojob',
            name='payment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.paymentstatus', verbose_name='payment status'),
        ),
    ]
