# Generated by Django 3.2.4 on 2021-07-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobs_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_status',
            field=models.CharField(choices=[('cr', 'Created'), ('co', 'Completed'), ('ur', 'Under review'), ('as', 'Assigned')], default='as', max_length=100),
        ),
    ]
