# Generated by Django 3.2.4 on 2021-06-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210624_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtojob',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs'),
        ),
    ]
