# Generated by Django 3.2.4 on 2021-07-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20210706_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microtask',
            name='microtask_category',
            field=models.CharField(choices=[('cw', 'Content Writing'), ('da', 'Document Analysis'), ('de', 'Data Entry'), ('cr', 'Combining Rules from Semi-Legal documents'), ('df', 'Data Entry(Fields)'), ('cd', 'Collecting copies of documents'), ('cp', 'Content Copy & Paste'), ('cf', 'Combining Data Entry Fields'), ('fn',
                                   'Find Non-Copyrighted Images and Uploading'), ('ac', 'Apply Compliance to Fields'), ('ng', 'Naming'), ('ce', 'Compliance Extraction'), ('id', 'Identifying One Line Decision'), ('ab', 'A+B TC For Document Extraction'), ('tc', 'TC For One Line Decision')], default='Content Writing', max_length=2, verbose_name='microtask category dropdown'),
        ),
    ]
