# Generated by Django 3.2.4 on 2021-06-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_mtojob_job_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mtoadminuser',
            managers=[
            ],
        ),
    ]
