# Generated by Django 3.2.4 on 2021-06-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_mtojob_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.mtojobcategory'),
        ),
    ]
