# Generated by Django 3.2.4 on 2021-07-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20210706_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentStatus',
        ),
    ]
