# Generated by Django 3.2.4 on 2021-06-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_paymentstatus_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs'),
        ),
    ]
