# Generated by Django 3.2.4 on 2021-07-07 12:01

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20210706_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='instructions',
            field=models.FileField(default='Onkar_py.txt', upload_to=jobs.models.instructions_directory_path),
        ),
        migrations.AddField(
            model_name='jobs',
            name='sample',
            field=models.FileField(default='Onkar_py.txt', upload_to=jobs.models.sample_directory_path),
        ),
    ]
