# Generated by Django 3.2.4 on 2021-06-27 11:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_mtoadminuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtojob',
            name='output_path',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='images/job_documents/job_submissions'), upload_to=''),
        ),
    ]
