# Generated by Django 3.2.4 on 2021-07-08 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20210707_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='person_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.adminroles'),
        ),
    ]
