# Generated by Django 3.2.4 on 2021-07-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20210707_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtoadminuser',
            name='department',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mtoadminuser',
            name='designation',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
