# Generated by Django 3.2.4 on 2021-06-27 11:41

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_mtojob_output_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtojob',
            name='output_path',
            field=models.FileField(upload_to=jobs.models.output_directory_path),
        ),
    ]
