# Generated by Django 3.2.4 on 2021-06-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_jobstatus_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstatus',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='paymentstatus',
            name='job_id',
        ),
    ]
