# Generated by Django 3.2.4 on 2021-07-08 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_jobs_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='person_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.mtoadminuser'),
        ),
    ]
