# Generated by Django 3.2.4 on 2021-07-08 12:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20210708_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtoadminuser',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
