# Generated by Django 3.2.4 on 2021-06-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_mtojob_output_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtojob',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
