# Generated by Django 3.2.4 on 2021-06-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_mtojob_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtojob',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
