# Generated by Django 3.2.4 on 2021-07-08 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_jobs_person_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobstatus',
        ),
        migrations.RemoveField(
            model_name='mtojob',
            name='is_submitted',
        ),
        migrations.AddField(
            model_name='jobs',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='microtask',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mtojob',
            name='submitted_date',
            field=models.DateTimeField(null=True),
        ),
    ]
