# Generated by Django 3.2.4 on 2021-06-27 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_mtojob_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtojob',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
