# Generated by Django 3.2.4 on 2021-07-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20210708_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='input_folder',
            field=models.CharField(max_length=300, verbose_name='input folder'),
        ),
    ]
