# Generated by Django 3.2.4 on 2021-06-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20210627_2048'),
        ('jobs', '0015_alter_mtojob_due_date'),
    ]

    operations = [
    ]
