# Generated by Django 3.2.4 on 2021-07-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_jobs_input_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='cat_id',
            field=models.CharField(max_length=50),
        ),
    ]
