# Generated by Django 3.2.4 on 2021-07-11 11:36

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_jobs_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='instructions',
            field=models.FileField(upload_to=jobs.models.instructions_directory_path),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='sample',
            field=models.FileField(upload_to=jobs.models.sample_directory_path),
        ),
    ]
