# Generated by Django 3.2.4 on 2021-06-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20210628_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobstatus',
            old_name='job_status_name',
            new_name='job_status',
        ),
    ]
