# Generated by Django 3.2.4 on 2021-07-11 11:57

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20210711_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='instructions',
            field=models.FileField(default='Varal.txt', upload_to=jobs.models.instructions_directory_path),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='sample',
            field=models.FileField(default='Varal.txt', upload_to=jobs.models.sample_directory_path),
        ),
    ]
