# Generated by Django 3.2.4 on 2021-07-11 13:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20210711_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtoadminuser',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='mtoadminuser',
            name='department',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mtoadminuser',
            name='designation',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
