# Generated by Django 3.2.4 on 2021-06-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_rename_job_status_name_jobstatus_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtojob',
            name='job_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobstatus', verbose_name='job status'),
        ),
    ]
