# Generated by Django 3.2.4 on 2021-07-08 10:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='department',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='designation',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
