# Generated by Django 3.2.4 on 2021-07-06 13:48

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTO',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('job_category', models.CharField(max_length=500, null=True)),
                ('paypal_id', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
