# Generated by Django 3.2.4 on 2021-06-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mto', '0003_auto_20210624_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mto',
            options={},
        ),
        migrations.AlterModelManagers(
            name='mto',
            managers=[
            ],
        ),
    ]
