# Generated by Django 3.2.4 on 2021-06-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mto', '0004_auto_20210627_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mto',
            name='job_category',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
