# Generated by Django 3.2.4 on 2021-06-29 11:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mto', '0005_alter_mto_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mto',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
