# Generated by Django 3.2.4 on 2021-06-29 14:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mto', '0006_alter_mto_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mto',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
