# Generated by Django 3.2.4 on 2021-07-01 08:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mto', '0007_alter_mto_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mto',
            name='location',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
